# Generated by Django 3.2.12 on 2023-11-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231118_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom kiriting')),
                ('body', models.TextField(max_length=100, verbose_name='malumot bering')),
                ('img', models.ImageField(upload_to='images', verbose_name='rasmni yuklang')),
            ],
        ),
    ]
